language: python
services:
  - docker
python:
  - "3.5"
  - "3.5-dev"
  - "3.6"
  - "3.6-dev"
  - "3.7"
  - "3.7-dev"
  - "3.8"
  - "3.8-dev"
  - "3.9-dev"
  - "nightly"
before_install:
  - pip install -U pip
  - pip install -U setuptools wheel
install:
  - pip install -r requirements.txt
  - pip install flake8 coverage codecov
script:
  - flake8 dockerjudge
  - python3 -W ignore -m coverage run tests.py
after_script:
  - codecov
